
//15. Write a Program to Demonstrate the Catching of all Exceptions.


#include <iostream>
using namespace std;
float division(int a,int b){
    string excep="Division by zero condition!";
    if (b!=0) return a/b;
    else throw excep;
}
int main(){
    int val1,val2;
    cout<<"Enter val1:";
    cin>>val1;
    cout<<"Enter val2:";
    cin>>val2;
    try{
       cout<<"val1/val2="<<division(val1,val2);
    }
    catch(string ex){
          cout<<ex;
    }
    return 0;
}

SAMPLE OUTPUT:
Enter val1:12
Enter val2:4
val1/val2=3

Enter val1:12
Enter val2:0
Division by zero condition!
